// console.log("hello world");
// console.log("mariyam saleem");
// document.write("hello world");
// alert("welcome to our website");
// let first_name;
// first_name ="mariyam";
// let last_name;
//  last_name =2024;
// console.log(last_name);
var birth = 43333;
var name = "mariyam saleem";
var email = "mariyamsaleeem87@gmail.com";
alert(name + "" + email + "    " + birth);